# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    tags:
      - v*.*.*
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Run
        
        working-directory: ./
        run: docker-compose up
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.39
        if: always()
        with:
          files: "results/*.xml"
          check_name: "Integration Test Results"
          check_run_annotations: "all tests"   