# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    tags:
      - v*.*.*
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Http Server
        run: |
            go run http-server.go &

      - name: Cypress Run
        env:
          CYPRESS_VIDEO: false
        working-directory: ./
        run: docker run --rm --network="host" -t -v $PWD:/tests -w /tests cypress/included:10.4.0 --config baseUrl=http://localhost:8090
      